name: provider_app
description: Remote Inventory Provider App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  
  # UI
  pin_code_fields: ^8.0.1
  
  # Camera
  camera: ^0.10.5
  
  # Sensors
  sensors_plus: ^3.0.0
  
  # gRPC
  grpc: ^3.2.0
  protobuf: ^3.1.0
  provider: ^6.1.0 # Added
  # Location services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Utilities
  intl: ^0.18.0
  permission_handler: ^11.0.0
  
  # For Consumer mode
  video_player: ^2.8.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
